### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by MaxwellWong-91** [anishg24/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] #2
  - does not show moving file from local to remote server
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by anishg24** [comment]
> does not show moving file from local to remote server

This is addressed in the [Moving Files with SCP](https://anishg24.github.io/cse15l-lab-reports/lab-report-1-week-2.html#moving-files-with-scp) section. A screenshot is provided to show how to transfer a C++ file to remote server.

**Comment by MaxwellWong-91** [comment]
While the Moving Files with SCP section covers that transfer, it is also required for the optimizing remote running portion. 

Here are the instructions for the optimize remote running portion.
"Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it."
